name: Main

on:
  push:
    branches: [main]

permissions:
  actions: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        arch: ['linux/amd64', 'linux/arm64']
        include:
          - file: 'fpm/Dockerfile'
            image-name-suffix: ''
          - file: 'apache/Dockerfile'
            image-name-suffix: '/apache'
    name: Build image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-images
        with:
          arch: ${{ matrix.arch }}
          cache-key: ${{ matrix.os }}-buildx-${{ matrix.arch }}-${{ github.ref_name }}-${{ github.sha }}
          cache-restore-keys: |
            ${{ matrix.os }}-buildx-${{ matrix.arch }}-${{ github.ref_name }}-
            ${{ matrix.os }}-buildx-${{ matrix.arch }}-
          file: ${{ matrix.file }}
          image-name-suffix: ${{ matrix.image-name-suffix }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
