name: Pull Requests

on:
  pull_request:

permissions:
  actions: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        arch: ['linux/amd64', 'linux/arm64']
        include:
          - file: 'fpm/Dockerfile'
            image-name-suffix: ''
          - file: 'apache/Dockerfile'
            image-name-suffix: '/apache'
    name: Build image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-images
        with:
          arch: ${{ matrix.arch }}
          cache-key: ${{ matrix.os }}-buildx-${{ matrix.arch }}-pr-${{ github.event.number }}-${{ github.sha }}
          cache-restore-keys: |
            ${{ matrix.os }}-buildx-${{ matrix.arch }}-pr-${{ github.event.number }}-
            ${{ matrix.os }}-buildx-${{ matrix.arch }}-pr-
            ${{ matrix.os }}-buildx-${{ matrix.arch }}-main-
          dockerfile: ${{ matrix.file }}
          image-name-suffix: ${{ matrix.image-name-suffix }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
